### ISSUE TITLE
final_weights.pth [questions]

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/LSM#6]
Hi there,
The model that you published `final_weights.pth` is amazing, it can generalize very well to unseen images.
- How did you train `final_weights.pth`, what options, image size, batch size, etc...?
- How many images did you use for training and testing?
- How many epochs did you train for, and how long did it take?
- `final_weights.pth` is 17.3MB while when i train, i get a model with size 31.1MB
- what is the purpose of `0.5` in [here](https://github.com/tson1997/Line-Segmentation-Model/commit/5882fb4f6856ad89efdca8178b6a0b7f1a16db32#diff-b280e787c26d56ad8d5812de993c496fe442871c5374f046805dfe24dcebf936L126)

**Comment by sonnguyenasu** [comment]
Hello, thank you for paying attention to the repo. 

- I trained with an exact similar config as I wrote the code in this repo
- I used 50000 images for training and 100 images for testing
- I trained the model for around 1 to 2 days (I let the code run on the weekend). Around 30k iterations if I remember correctly
- It is actually the model with bilinear upsampling (UNet(3,1,bilinear=True) option). Therefore it is around half lighter. However, I changed the config afterwards so that the model can be converted to tensorrt easily. I forgot to change it back, it is my bad.
- 0.5 has no meaning, that's why I removed it :D (at first it is the scale parameter that I found from UNet, but I do not use it in my code)

**Comment by sonnguyenasu** [comment]
By the way, if you want to train the model with bilinear upsample, you can change [this line](https://github.com/tson1997/Line-Segmentation-Model/blob/05db96ecba520c66146cc42f4808ac8ebae7e24f/train.py#L30) and change [this line](https://github.com/tson1997/Line-Segmentation-Model/blob/05db96ecba520c66146cc42f4808ac8ebae7e24f/demo.py#L99) from demo.py

**Comment by seekingdeep** [comment]
Thanks
by the way, SDL results looks promising, as the more variations, augmentation, orientation, etc... the model sees, the better it can generalize to unseen images. [DCE](http://imagine.enpc.fr/~monniert/docExtractor/) even found that you can simply train a model on sythetic data and it still would be able to achieve SOTA results by-default, and [after fine-tuning](https://youtu.be/Tuw8uQonW7E?t=581) it could be on-par with the best models.
